version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - '${FRONTEND_PORT:-3001}:3001'
    volumes:
      - .:/app
      - /app/node_modules

  storybook:
    build:
      context: .
      dockerfile: Dockerfile.storybook
    ports:
      - '${STORYBOOK_PORT:-6006}:6006'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
